# Generated by Django 5.1.6 on 2025-04-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('writer', 'Writer'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
