# Generated by Django 5.1.6 on 2025-04-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departement',
            field=models.CharField(choices=[('logistic', 'logistic'), ('media', 'media'), ('management', 'management'), ('other', 'other')], default='other', max_length=20),
        ),
    ]
