# Generated by Django 5.1.6 on 2025-05-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(default='defaul description', max_length=120),
            preserve_default=False,
        ),
    ]
